services:
  app:
    build: .
    command: ["--type", "web", "--log", "--pgsql", "db:5432", "--redis", "redis:6379"]
    container_name: studio
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: studio
      POSTGRES_PASSWORD: studio
      POSTGRES_DB: studio
      POSTGRES_SCHEME: studio
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always

volumes:
  pgdata:
